
<option value="" disabled selected>- Select -</option>
<option value="1" @if($val == 1) {{'selected'}} @endif>01</option>
<option value="2" @if($val == 2) {{'selected'}} @endif>02</option>
<option value="3" @if($val == 3) {{'selected'}} @endif>03</option>
<option value="4" @if($val == 4) {{'selected'}} @endif>04</option>
<option value="5" @if($val == 5) {{'selected'}} @endif>05</option>
<option value="6" @if($val == 6) {{'selected'}} @endif>06</option>
<option value="7" @if($val == 7) {{'selected'}} @endif>07</option>
<option value="8" @if($val == 8) {{'selected'}} @endif>08</option>
<option value="9" @if($val == 9) {{'selected'}} @endif>09</option>
<option value="10" @if($val == 10) {{'selected'}} @endif>10</option>
<option value="11" @if($val == 11) {{'selected'}} @endif>11</option>
<option value="12" @if($val == 12) {{'selected'}} @endif>12</option>
<option value="13" @if($val == 13) {{'selected'}} @endif>13</option>
<option value="14" @if($val == 14) {{'selected'}} @endif>14</option>
<option value="15" @if($val == 15) {{'selected'}} @endif>15</option>
<option value="16" @if($val == 16) {{'selected'}} @endif>16</option>
<option value="17" @if($val == 17) {{'selected'}} @endif>17</option>
<option value="18" @if($val == 18) {{'selected'}} @endif>18</option>
<option value="19" @if($val == 19) {{'selected'}} @endif>19</option>
<option value="20" @if($val == 20) {{'selected'}} @endif>20</option>
<option value="21" @if($val == 21) {{'selected'}} @endif>21</option>
<option value="22" @if($val == 22) {{'selected'}} @endif>22</option>
<option value="23" @if($val == 23) {{'selected'}} @endif>23</option>
<option value="24" @if($val == 24) {{'selected'}} @endif>24</option>
<option value="25" @if($val == 25) {{'selected'}} @endif>25</option>
<option value="26" @if($val == 26) {{'selected'}} @endif>26</option>
<option value="27" @if($val == 27) {{'selected'}} @endif>27</option>
<option value="28" @if($val == 28) {{'selected'}} @endif>28</option>
<option value="29" @if($val == 29) {{'selected'}} @endif>29</option>
<option value="30" @if($val == 30) {{'selected'}} @endif>30</option>
<option value="31" @if($val == 31) {{'selected'}} @endif>31</option>
<option value="32" @if($val == 32) {{'selected'}} @endif>32</option>
<option value="33" @if($val == 33) {{'selected'}} @endif>33</option>
<option value="34" @if($val == 34) {{'selected'}} @endif>34</option>
<option value="35" @if($val == 35) {{'selected'}} @endif>35</option>
<option value="36" @if($val == 36) {{'selected'}} @endif>36</option>
<option value="37" @if($val == 37) {{'selected'}} @endif>37</option>
<option value="38" @if($val == 38) {{'selected'}} @endif>38</option>
<option value="39" @if($val == 39) {{'selected'}} @endif>39</option>
<option value="40" @if($val == 40) {{'selected'}} @endif>40</option>
<option value="41" @if($val == 41) {{'selected'}} @endif>41</option>
<option value="42" @if($val == 42) {{'selected'}} @endif>42</option>
<option value="43" @if($val == 43) {{'selected'}} @endif>43</option>
<option value="44" @if($val == 44) {{'selected'}} @endif>44</option>
<option value="45" @if($val == 45) {{'selected'}} @endif>45</option>
<option value="46" @if($val == 46) {{'selected'}} @endif>46</option>
<option value="47" @if($val == 47) {{'selected'}} @endif>47</option>
<option value="48" @if($val == 48) {{'selected'}} @endif>48</option>
<option value="49" @if($val == 49) {{'selected'}} @endif>49</option>
<option value="50" @if($val == 50) {{'selected'}} @endif>50</option>
<option value="51" @if($val == 51) {{'selected'}} @endif>51</option>
<option value="52" @if($val == 52) {{'selected'}} @endif>52</option>
<option value="53" @if($val == 53) {{'selected'}} @endif>53</option>
<option value="54" @if($val == 54) {{'selected'}} @endif>54</option>
<option value="55" @if($val == 55) {{'selected'}} @endif>55</option>
<option value="56" @if($val == 56) {{'selected'}} @endif>56</option>
<option value="57" @if($val == 57) {{'selected'}} @endif>57</option>
<option value="58" @if($val == 58) {{'selected'}} @endif>58</option>
<option value="59" @if($val == 59) {{'selected'}} @endif>59</option>
<option value="60" @if($val == 60) {{'selected'}} @endif>60</option>
<option value="61" @if($val == 61) {{'selected'}} @endif>61</option>
<option value="62" @if($val == 62) {{'selected'}} @endif>62</option>
<option value="63" @if($val == 63) {{'selected'}} @endif>63</option>
<option value="64" @if($val == 64) {{'selected'}} @endif>64</option>
<option value="65" @if($val == 65) {{'selected'}} @endif>65</option>
<option value="66" @if($val == 66) {{'selected'}} @endif>66</option>
<option value="67" @if($val == 67) {{'selected'}} @endif>67</option>
<option value="68" @if($val == 68) {{'selected'}} @endif>68</option>
<option value="69" @if($val == 69) {{'selected'}} @endif>69</option>
<option value="70" @if($val == 70) {{'selected'}} @endif>70</option>
<option value="71" @if($val == 71) {{'selected'}} @endif>71</option>
<option value="72" @if($val == 72) {{'selected'}} @endif>72</option>
<option value="73" @if($val == 73) {{'selected'}} @endif>73</option>
<option value="74" @if($val == 74) {{'selected'}} @endif>74</option>
<option value="75" @if($val == 75) {{'selected'}} @endif>75</option>
<option value="76" @if($val == 76) {{'selected'}} @endif>76</option>
<option value="77" @if($val == 77) {{'selected'}} @endif>77</option>
<option value="78" @if($val == 78) {{'selected'}} @endif>78</option>
<option value="79" @if($val == 79) {{'selected'}} @endif>79</option>
<option value="80" @if($val == 80) {{'selected'}} @endif>80</option>
<option value="81" @if($val == 81) {{'selected'}} @endif>81</option>
<option value="82" @if($val == 82) {{'selected'}} @endif>82</option>
<option value="83" @if($val == 83) {{'selected'}} @endif>83</option>
<option value="84" @if($val == 84) {{'selected'}} @endif>84</option>
<option value="85" @if($val == 85) {{'selected'}} @endif>85</option>
<option value="86" @if($val == 86) {{'selected'}} @endif>86</option>
<option value="87" @if($val == 87) {{'selected'}} @endif>87</option>
<option value="88" @if($val == 88) {{'selected'}} @endif>88</option>
<option value="89" @if($val == 89) {{'selected'}} @endif>89</option>
<option value="90" @if($val == 90) {{'selected'}} @endif>90</option>
<option value="91" @if($val == 91) {{'selected'}} @endif>91</option>
<option value="92" @if($val == 92) {{'selected'}} @endif>92</option>
<option value="93" @if($val == 93) {{'selected'}} @endif>93</option>
<option value="94" @if($val == 94) {{'selected'}} @endif>94</option>
<option value="95" @if($val == 95) {{'selected'}} @endif>95</option>
<option value="96" @if($val == 96) {{'selected'}} @endif>96</option>
<option value="97" @if($val == 97) {{'selected'}} @endif>97</option>
<option value="98" @if($val == 98) {{'selected'}} @endif>98</option>
<option value="99" @if($val == 99) {{'selected'}} @endif>99</option>
<option value="100" @if($val == 100) {{'selected'}} @endif>100</option>
