<option value="" selected disabled>-Select-</option>
<option value="1" @if($val == 1) {{'selected'}} @endif>01</option>
<option value="2" @if($val == 2) {{'selected'}} @endif>02</option>
<option value="3" @if($val == 3) {{'selected'}} @endif>03</option>
<option value="4" @if($val == 4) {{'selected'}} @endif>04</option>
<option value="5" @if($val == 5) {{'selected'}} @endif>05</option>
<option value="6" @if($val == 6) {{'selected'}} @endif>06</option>
<option value="7" @if($val == 7) {{'selected'}} @endif>07</option>
<option value="8" @if($val == 8) {{'selected'}} @endif>08</option>
<option value="9" @if($val == 9) {{'selected'}} @endif>09</option>
<option value="10" @if($val == 10) {{'selected'}} @endif>10</option>
<option value="11" @if($val == 11) {{'selected'}} @endif>11</option>
<option value="12" @if($val == 12) {{'selected'}} @endif>12</option>
<option value="13" @if($val == 13) {{'selected'}} @endif>13</option>
<option value="14" @if($val == 14) {{'selected'}} @endif>14</option>
<option value="15" @if($val == 15) {{'selected'}} @endif>15</option>
<option value="16" @if($val == 16) {{'selected'}} @endif>16</option>
<option value="17" @if($val == 17) {{'selected'}} @endif>17</option>
<option value="18" @if($val == 18) {{'selected'}} @endif>18</option>
<option value="19" @if($val == 19) {{'selected'}} @endif>19</option>
<option value="20" @if($val == 20) {{'selected'}} @endif>20</option>
<option value="21" @if($val == 21) {{'selected'}} @endif>21</option>
<option value="22" @if($val == 22) {{'selected'}} @endif>22</option>
<option value="23" @if($val == 23) {{'selected'}} @endif>23</option>
<option value="24" @if($val == 24) {{'selected'}} @endif>24</option>
<option value="25" @if($val == 25) {{'selected'}} @endif>25</option>
<option value="26" @if($val == 26) {{'selected'}} @endif>26</option>
<option value="27" @if($val == 27) {{'selected'}} @endif>27</option>
<option value="28" @if($val == 28) {{'selected'}} @endif>28</option>
